[package]
name = "twentyletters_analysis_tool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
chrono = "0.4"
lazy_static = "1.4.0"